version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: vitrine-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: vitrine

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    command: sh -c "node seed.js && npm run dev"


  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend


  tests:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    command: ["npm", "test"]
    
volumes:
  mongodb_data: